server:
  port: 9292

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: root123  
  jpa:
    hibernate:
      ddl-auto: update    

sms-provider:
  clientId: eskiz
  clientSecret: secretKey233
  loginSms: 'Sizning app.shop.uz kirish parolingiz : %s'  
